import Link from "next/link";
import DomainSearch from "@/components/DomainSearch";
import PackageCards from "@/components/PackageCards";

export default function HomePage() {
  return <main className="product-home">
    <section className="product-hero"><div className="product-hero-copy"><p className="eyebrow">MỘT NGỤM / DIGITAL STUDIO</p><h1>Website của bạn bắt đầu bằng một cái tên.</h1><p className="hero-lede">Tìm tên miền, chọn một website vừa đủ và để Một Ngụm lo phần kỹ thuật.</p><a className="hero-link" href="#domain-search">Bắt đầu với tên miền <span>↓</span></a></div><div className="hero-aside"><span>01</span><p>Không cần biết mình cần gì.<br />Chỉ cần biết mình muốn bắt đầu.</p></div></section>
    <section className="product-section domain-section"><div className="section-label">01 / TÊN MIỀN</div><div className="section-intro"><h2>Một thương hiệu tốt nên có một địa chỉ rõ ràng.</h2><p>Nhập tên bạn đang nghĩ đến. Xem các đuôi phổ biến, giá tham khảo và chọn tên hợp với hướng đi của bạn.</p></div><DomainSearch /></section>
    <section className="product-section offer-section"><div className="section-label">02 / WEBSITE</div><div className="section-intro"><h2>Chọn phần bạn cần. Phần còn lại để chúng tôi lo.</h2><p>Không có bảng giá rối. Mỗi gói là một điểm bắt đầu rõ ràng, có thể mở rộng khi công việc thay đổi.</p></div><div className="offer-list"><div><strong>01</strong><h3>Website bán hàng</h3><p>Biến lượt ghé thăm thành cuộc trò chuyện và đơn hàng.</p></div><div><strong>02</strong><h3>Website doanh nghiệp</h3><p>Giới thiệu thương hiệu bằng một diện mạo đáng tin.</p></div><div><strong>03</strong><h3>Landing page</h3><p>Tập trung một sản phẩm, một chiến dịch, một hành động.</p></div></div></section>
    <section className="product-section packages-section" id="packages"><div className="section-label">03 / BÁO GIÁ WEBSITE</div><div className="section-intro"><h2>Rõ giá. Rõ phạm vi. Dễ lựa chọn.</h2><p>Chọn loại website để xem mức giá tham khảo. Một Ngụm sẽ xác nhận giá cuối cùng sau khi hiểu đúng nhu cầu của bạn.</p></div><PackageCards /></section>
    <section className="product-section process-section"><div className="section-label">04 / CÁCH LÀM</div><div className="process-copy"><h2>Từ một ý tưởng đến một website có người chịu trách nhiệm.</h2><ol><li><b>Chia sẻ</b><span>Kể chúng tôi nghe bạn đang làm gì.</span></li><li><b>Chọn</b><span>Chọn tên, gói và hướng hình ảnh.</span></li><li><b>Nhận bàn giao</b><span>Website, domain, email — gọn trong một lần làm.</span></li></ol></div></section>
    <section className="product-cta"><p className="eyebrow">Sẵn sàng bắt đầu?</p><h2>Một ngụm là đủ để mở lời.</h2><p>Hãy kể việc bạn muốn làm rõ. Chúng tôi sẽ trả lời bằng một hướng đi cụ thể.</p><Link href="/lien-he" className="button button-dark">Nhận tư vấn miễn phí →</Link></section>
  </main>;
}
